### ISSUE TITLE
advice about the teach plan table

### ISSUE THREAD

**Issue by wangding** [liujinmenghaoren/web#1]
![advice1](https://cloud.githubusercontent.com/assets/1182720/22818176/accf3534-efa6-11e6-8884-37f737d2743d.png)

**Comment by liujinmenghaoren** [comment]
![_2017-02-13t02-15-25 803z](https://cloud.githubusercontent.com/assets/22046197/22868866/73838cea-f1d5-11e6-873e-b780cd918527.png)
已将表格完善。 @wangding
