### ISSUE TITLE
advice about ignore the .project file

### ISSUE THREAD

**Issue by wangding** [liujinmenghaoren/web#2]
![advice2](https://cloud.githubusercontent.com/assets/1182720/22818222/0129176c-efa7-11e6-85c9-4d08e71304fa.png)

the .gitignore file, you can see in wangding/courses

**Comment by liujinmenghaoren** [comment]
问题已解决，并记录[笔记](https://github.com/liujinmenghaoren/myNote/blob/master/git/ignore.md)。 @wangding
